#!/usr/bin/env python3
"""Differential test data for rhombus/hol/private/format.rhm.

    python3 tools/hol_light_golden/format_oracle.py

Generates random sequences of Format calls (boxes of every kind, strings,
breaks, spaces, cuts, forced newlines, pp_print_as, margins, max_boxes),
runs them through OCaml's own Format (needs `ocaml` 4.14 on PATH) and writes
rhombus/hol/tests/format_oracle.rhm, which replays them on the Rhombus
translation and requires the same output.
"""
import json
import os
import random
import subprocess
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', '..', 'rhombus', 'hol', 'tests', 'format_oracle.rhm')


def programs():
    random.seed(7)
    progs = []
    for _ in range(60):
        ops = []; depth = 0
        margin = random.choice([20, 30, 40, 78])
        maxboxes = random.choice([None, None, 3, 5])
        for _ in range(random.randint(5, 60)):
            r = random.random()
            if r < 0.2:
                ops.append([random.choice(['box', 'hvbox', 'hovbox', 'vbox', 'hbox']), random.randint(0, 4)]); depth += 1
            elif r < 0.3 and depth > 0:
                ops.append(['close', 0]); depth -= 1
            elif r < 0.55:
                ops.append(['str', random.choice(['a', 'bb', 'ccc', 'word', 'longer_word', 'x+y', '(f x)', 'forall'])])
            elif r < 0.7:
                ops.append(['break', random.randint(0, 3), random.randint(-2, 4)])
            elif r < 0.8:
                ops.append(['space', 0])
            elif r < 0.86:
                ops.append(['cut', 0])
            elif r < 0.9:
                ops.append(['newline', 0])
            else:
                ops.append(['as', random.randint(0, 5), 'ab'])
        progs.append({'margin': margin, 'maxboxes': maxboxes, 'ops': ops})
    return progs


def ocaml_program(progs):
    out = ['let buf = Buffer.create 100;;',
           'let run margin maxb f = Buffer.reset buf; '
           'let fmt = Format.formatter_of_buffer buf in Format.pp_set_margin fmt margin; '
           '(match maxb with Some n -> Format.pp_set_max_boxes fmt n | None -> ()); '
           'f fmt; Format.pp_print_flush fmt (); '
           'print_string (String.escaped (Buffer.contents buf)); print_newline ();;']
    for p in progs:
        body = []
        for o in p['ops']:
            t = o[0]
            if t in ('box', 'hvbox', 'hovbox', 'vbox'): body.append(f'Format.pp_open_{t} fmt {o[1]}')
            elif t == 'hbox': body.append('Format.pp_open_hbox fmt ()')
            elif t == 'close': body.append('Format.pp_close_box fmt ()')
            elif t == 'str': body.append(f'Format.pp_print_string fmt {json.dumps(o[1])}')
            elif t == 'break': body.append(f'Format.pp_print_break fmt {o[1]} ({o[2]})')
            elif t == 'space': body.append('Format.pp_print_space fmt ()')
            elif t == 'cut': body.append('Format.pp_print_cut fmt ()')
            elif t == 'newline': body.append('Format.pp_force_newline fmt ()')
            elif t == 'as': body.append(f'Format.pp_print_as fmt {o[1]} {json.dumps(o[2])}')
        mb = 'None' if p['maxboxes'] is None else f"Some {p['maxboxes']}"
        out.append(f"run {p['margin']} ({mb}) (fun fmt -> {'; '.join(body) if body else '()'});;")
    return '\n'.join(out) + '\n'


def unescape(s):
    # OCaml's String.escaped of ASCII text
    return s.encode().decode('unicode_escape')


def rhombus_string(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n') + '"'


def rhombus_op(o):
    return '[' + ', '.join(rhombus_string(x) if isinstance(x, str) else str(x) for x in o) + ']'


def main():
    progs = programs()
    with tempfile.NamedTemporaryFile('w', suffix='.ml', delete=False) as f:
        f.write(ocaml_program(progs))
        name = f.name
    out = subprocess.run(['ocaml', name], capture_output=True, text=True, check=True).stdout
    os.unlink(name)
    expected = [unescape(l) for l in out.rstrip('\n').split('\n')]
    assert len(expected) == len(progs)
    lines = ['#lang rhombus',
             '// Differential test of private/format.rhm against OCaml 4.14 Format.',
             '// Generated by tools/hol_light_golden/format_oracle.py; do not edit.',
             'import:',
             '  "../private/format.rhm" open',
             '',
             'fun run(margin, maxboxes, ops :: List):',
             '  let b = OCamlBuffer.create(#void)',
             '  let fmt = Format.formatter_of_buffer(b)',
             '  Format.pp_set_margin(fmt)(margin)',
             '  when maxboxes | Format.pp_set_max_boxes(fmt)(maxboxes)',
             '  for (op in ops):',
             '    match op',
             '    | ["box", n]: Format.pp_open_box(fmt)(n)',
             '    | ["hvbox", n]: Format.pp_open_hvbox(fmt)(n)',
             '    | ["hovbox", n]: Format.pp_open_hovbox(fmt)(n)',
             '    | ["vbox", n]: Format.pp_open_vbox(fmt)(n)',
             '    | ["hbox", _]: Format.pp_open_hbox(fmt)(#void)',
             '    | ["close", _]: Format.pp_close_box(fmt)(#void)',
             '    | ["str", s]: Format.pp_print_string(fmt)(s)',
             '    | ["break", w, o]: Format.pp_print_break(fmt)(w)(o)',
             '    | ["space", _]: Format.pp_print_space(fmt)(#void)',
             '    | ["cut", _]: Format.pp_print_cut(fmt)(#void)',
             '    | ["newline", _]: Format.pp_force_newline(fmt)(#void)',
             '    | ["as", n, s]: Format.pp_print_as(fmt)(n)(s)',
             '  Format.pp_print_flush(fmt)(#void)',
             '  OCamlBuffer.contents(b)',
             '']
    for p, e in zip(progs, expected):
        ops = '[' + ', '.join(rhombus_op(o) for o in p['ops']) + ']'
        mb = '#false' if p['maxboxes'] is None else str(p['maxboxes'])
        lines.append(f"check run({p['margin']}, {mb}, {ops}) ~is {rhombus_string(e)}")
    open(OUT, 'w').write('\n'.join(lines) + '\n')
    print(f'wrote {len(progs)} cases to {os.path.relpath(OUT)}')


if __name__ == '__main__':
    main()
