#lang racket/base
(require racket/match)
(define m '(file "../../rhombus/hol/fusion.rhm"))
;; run from tests/; constructors must be unavailable even through dynamic-require.
(for ([name '(Tyvar Tyapp Var Const Comb Abs Sequent KernelTyvar KernelTyapp KernelVar KernelConst KernelComb KernelAbs)])
  (define absent? (with-handlers ([exn:fail? (lambda (_) #t)]) (dynamic-require m name) #f))
  (unless absent? (error 'privacy "constructor exported: ~a" name))
  (printf "~a: hidden\n" name))
(define make-var (dynamic-require m 'mk_var))
(define bool-ty (dynamic-require m 'bool_ty))
(define refl (dynamic-require m 'REFL))
(define v (make-var (cons "x" bool-ty)))
(for ([obj (list bool-ty v (refl v))] [name '(type term theorem)])
  (define-values (descriptor skipped?) (struct-info obj))
  (unless (not descriptor) (error 'privacy "descriptor exposed: ~a" name))
  (printf "~a: opaque descriptor\n" name))
(for ([entry (list (list 'mk_vartype 42)
                   (list 'mk_var (cons "x" 42))
                   (list 'mk_type (cons "fun" (list 42 bool-ty)))
                   (list 'mk_const (cons "=" (list (cons 42 bool-ty))))
                   (list 'new_constant (cons "bad" 42))
                   (list 'REFL #t)
                   (list 'ASSUME #t)
                   (list 'vsubst (list (cons #t v))))])
  (define rejected? (with-handlers ([exn:fail? (lambda (_) #t)])
                      ((dynamic-require m (car entry)) (cadr entry)) #f))
  (unless rejected? (error 'privacy "invalid host argument accepted: ~a" (car entry)))
  (printf "~a: rejects invalid host argument\n" (car entry)))